### ISSUE TITLE
授权失败

### ISSUE THREAD

**Issue by aogg** [SwooleDistributed/SwooleDistributed3.X-Dockerfile#1]
$ docker-compose up -d
Creating network "liveservice_default" with the default driver
Pulling swoole (ccr.ccs.tencentyun.com/plugin/plugin-docker:0.0.1)...
ERROR: Get https://ccr.ccs.tencentyun.com/v2/plugin/plugin-docker/manifests/0.0.1: unauthorized: authentication required

**Comment by gaowenfei2013** [comment]
This is just an example. You need build image with docker
